Food_Bloggers/FBvirenv/Food_Bloggers/Food_Bloggers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from .views import  HomeListView, RegisterUserView



urlpatterns = [

    path('admin/', admin.site.urls),

    path('', HomeListView.as_view(), name='home'), 

    path('login/', LoginView.as_view(), name='login'),       #no views only TEMPLATE needed

    path('logout/', LogoutView.as_view(), name='logout'),    #no VIEWS no template needed

    path('register/', RegisterUserView.as_view(), name='register'),

    path('accounts/', include('django.contrib.auth.urls')),  #Used for password reset url only 


    #local_apps goes here ... 
    path('restaurant/', include('restaurantApp.urls')), 

]


if settings.DEBUG: 
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Food_Bloggers/FBvirenv/Food_Bloggers/restaurantApp/models.py
from django.db import models
from datetime import date 
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.



class Restaurant(models.Model):
    name          = models.CharField(max_length=300)
    street        = models.CharField(max_length=300)
    city          = models.CharField(max_length=100, default='Barishal')
    district      = models.CharField(max_length=100, default='Barishal')
    country       = models.CharField(max_length=100, default='Bangladesh')
    telephone     = models.CharField(max_length=100, blank=True, null=True)
    url           = models.URLField(max_length=200, blank=True, null=True)
    date          = models.DateField(default=date.today)
    image         = models.ImageField()
    user          = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurant-detail', kwargs={'pk': self.pk})



class Dish(models.Model):
    name         = models.CharField(max_length=200)
    description  = models.TextField()
    price        = models.DecimalField(max_digits=8, decimal_places=2)
    user         = models.ForeignKey(User, on_delete=models.CASCADE)
    date         = models.DateField(default=date.today)
    image        = models.ImageField(blank=True, null=True)
    restaurant   = models.ForeignKey(Restaurant, related_name='dishes', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dishes-detail', kwargs={
            'pkr': self.restaurant.id,
            'pk': self.id
        })



class Review(models.Model):
    RATING_CHOICES    = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating            = models.PositiveSmallIntegerField('Rating Stars', blank=False, default=3,choices=RATING_CHOICES)
    comment           = models.TextField()
    user              = models.ForeignKey(User, on_delete=models.CASCADE)
    date              = models.DateField(default=date.today)

    class Meta:
        abstract = True



class RestaurantReview(Review):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

Food_Bloggers/FBvirenv/Food_Bloggers/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title%} {% endblock %}</title>

  {% include 'base/css.html' %}

  {% block stylesheet %} {% endblock %}

</head>

<body>
  {% include 'base/navbar.html' %}

  <!-- Page Content -->
  <div class="container">

        {% block slider %}
            {% include 'base/slider.html' %} 
        {% endblock %}   

    <!-- Content Row -->
    <div class="row my-3">

        {% block carosel %}

        {% endblock %}
        
        {% block content %}




        {% endblock %}

        {% block pagination %}
        
        {% endblock %}
      

    </div>
    <!-- /.row -->
    

  </div>
  <!-- /.container -->

  <!-- Footer -->

      <footer class="py-3 bg-info">
          <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Food Bloggers 2019</p>
          </div>
      </footer>


  <!-- Bootstrap core JavaScript -->
  {% include 'base/js.html'%}

</body>

</html>

Food_Bloggers/FBvirenv/Food_Bloggers/templates/home_list.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block slider %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container">
            <div class="row justify-content-md-center my-5 ">
                    <div class="col col-lg-4">
                      <h1 class="text-info" style="font-family: 'Oswald', sans-serif;">RESTAURANTS</h1>   
                    </div>
                    <div class="col-lg-auto ">
                      
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="col col-lg-4">
                        <h1 class="text-info" style="font-family: 'Oswald', sans-serif;"><a href="{% url 'restaurant-create' %}">ADD RESTAURANTS</a></h1>
                    </div>
                    {% endif %}
                  </div>
    </div>
    
    <div class="row mx-auto">
          

                {% for rlist in restaurant_list %}
    
                <div class="col-md-4 mb-5">
                    <div class="card">
                      <a href="{% url 'restaurant-detail' rlist.id %}"><img src="{{ rlist.image.url }}" alt="{{ rlist.title }} picture" width="348px" height="300px"></a>
                      <div class="card-body">
                        
                        <h4 class="card-title"><b>{{ rlist.name }}</b></h4>
        
                        <p> {{ rlist.street }}, {{ rlist.city }}, {{ rlist.district }}, {{ rlist.country }}</p>
                        
                      </div>
                      <div class="card-footer">
                        <a href="{% url 'restaurant-detail' rlist.id %}" class="btn btn-info btn-sm">Review</a>
                      </div>
                    </div>
                </div>
                {% empty %}
                    <li>Sorry, no restaurants registered yet.</li>
                {% endfor %}

    </div>
    <div class="row mx-auto">
                {% if is_paginated %}
                <nav aria-label="Page navigation example"></nav>
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                            </a>
                        </li>
        
                    {% endif %}
                    
                    {% for i in page_obj.paginator.page_range %}
                        
                    {% if page_obj.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
        
                    {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        
                    {% endif %}
        
                    {% endfor %}
                    
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                            </a>
                        </li>
        
                    {% endif %}
                </ul>
                </nav>
            {% endif %}


    </div>
    

    <!-- pagination starts from here -->

                         



{% endblock %}

Food_Bloggers/FBvirenv/Food_Bloggers/templates/test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- font awesome -->
    <link href="https://fonts.googleapis.com/css?family=Righteous" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>




    

    <div class="card m-auto">
        <div class="row ">
            <div class="col col-md-6">
                    <h3 class="card-header text-left text-info" style="font-family: 'Oswald', sans-serif;"><b><i class="fas fa-file-signature"></i>&nbsp;&nbsp;REVIEWS</b> </h3>
            </div>
            {% if request.user.is_authenticated %}
                <div class="col col-md-6">
                        <h3 class="card-header text-info text-right"><b>Add a Reviews</b></h3>
                </div>
            {% else %}
                <div class="col col-md-6">
                    <h3 class="card-header text-info text-right"><b><a href="{% url 'login' %}" role="button">Login to Add Reviews</a></b></h3>
                </div>
            {% endif %}
        <!-- </div> -->
            
            <div class="card-body">
                <div class="row">

                    <div class="col-md-6">

                        {% for review in restaurant_object.restaurantreview_set.all %}
                            <h5 class="card-title"><b><i class="fas fa-user-circle"></i> {{ review.user }}</b><small> on {{ review.date }}</small> </h5>
                            <p class="card-text"><b class="text text-info"> {{ review.rating }} Star{{ review.rating|pluralize }} </b>{{ review.comment }}</p><hr>
                        {% empty %}
                            <li>Sorry, no reviews for this restaurant yet. You can add a review. </li>
                        {% endfor %}
                        
                    </div>
                    <div class="col-md-6">
                        <form action="{% url 'review-create' restaurant_object.id %}" method="POST">
                            {% csrf_token %}
                            <b>Comment: </b><br><textarea name="comment" id="comment" rows="" class="form-control"></textarea>

                            <p class="mt-3"><b>Rating:</b></p>

                            {% for rate in RATING_CHOICES %}
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.0 }}" />
                                <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label><br/>
                            {% endfor %}

                            <input type="submit" value="Review" class="text text-info"/>
                        </form>
                    </div>
                </div>
              
            </div>
        </div> <!-- row end -->
    </div>




























    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>